#!/usr/bin/env bash

################################################
# PROGRAM:
# `summitRNAseq_PE_analyzer.sh`
#
# DESCRIPTION:
# An RNA-seq pipeline for usage on the RMACC Summit Compute Cluster. The Singularity container 
# `summitRNAseq.simg` was built to work alongside this pipeline. This RNA-seq pipeline will analyze 
# paired-end (PE) FASTQ sequencing reads generated by the Illumina sequencing platform. This 
# pipeline will perform quality control, read trimming, genome alignment, basic format
# conversions, and featureCounts tabulation for paired-end RNA-seq samples using a specified
# genome. 
#
# AUTHOR:
# Robert Thomas Patton Williams, modified from Erin Osborne Nishimura
#
# START DATE:
# July 10, 2019
#
# CONTAINER:
# `summitRNAseq.simg`
#
#   See https://github.com/rtpwilliams/Summit_RNAseq_container for Singularity build recipe. To 
#   download this container type the following command:
#
#               $ singularity pull shub://rtpwilliams/Summit_RNAseq_container:master
#
#  This container provides the following software:
#  - fastp=0.20.0
#  - hisat2=2.1.0
#  - picard=2.18.27
#  - conda-forge::r-data.table=1.12.0
#  - conda-forge::r-gplots=3.0.1.1
#  - bioconductor-deseq2=1.22.1
#  - conda-forge::r-markdown=0.9
#  - samtools=1.9
#  - deeptools=3.2.0
#  - bedtools=2.28.0
#  - htseq=0.11.2
#  - subread=1.6.4
#
# 
#
# REQUIRES:
#    INPUT: .fastq files.    For each sample, paired forward and reverse sequencing files
#								are required. These should be placed in an input
#								directory.
#
#    INPUT: _metadata.txt file: A tab-separated metadata file with at least one columns. The first 
#								column is the fastq file name for read one (R1) without the `.fastq.gz` suffix. 
#               The second column is a fastq file name for read two (R2) without the `.fastq.gz` suffix
#               The third column contains a "nickname" of each sample that will be used for directory
#               naming. Additional columns can be included with other metadata information.
#								The Metadata file should be placed within the `inputdir` directory.
#
#
#    HISAT2 INDEXES: `.ht2` files for the genome. These are produced using `hisat2-build`. For
#								instructions see
#	           https://ccb.jhu.edu/software/hisat2/manual.shtml#the-hisat2-build-indexer
#
#    GENOME SEQUENCE: `.fa`  or `.tar.gz` file for the genome. This is the sequence of the 
#                                genome.
#
#    GENOME ANNOTATION: `.gtf` file for the genome. This is a genome annotation file of gene
#								features. Version and coordinates must match the genome
#								sequence (.fa above).
#
# USAGE:
# $ bash summitRNAseq_SE_analyzer.sh <metadata.txt> <number of threads>
#
# OUTPUT:
#
# KNOWN BUGS:
#
# THINGS TO IMPROVE:
# Add singularity hub link once the server is back up.
# Align reads to ERCC spike in file
# Explicitly give fastp the adapter sequences - Done, needs testing
################################################


echo -e ">>> INITIATING analyzer with command:\n \t $0 $@"

########### SUPPLY A CONFIG FILE TO SPECIFY FILE AND COMMAND LOCATIONS 
source PE_WS263_ce11.config
#######################################################################

#This is the output_directory:


echo -e ">>> MAKING output directory"
echo -e "\t mkdir $outputdir"
mkdir -p $outputdir

####### META DATA #############

#These are the sample files for read 1 (R1):
sample1=( $(cut -f 1 --output-delimiter='\t' $1) )

echo $sample1

#These are the sample files for read 2 (R2):
sample2=( $(cut -f 2 --output-delimiter='\t' $1) )

echo $sample2

#These are the nicknames I want to give the files:
names=( $(cut -f 3 --output-delimiter='\t' $1) )
echo $names


 ####### PIPELINE ##############

# Report back to the user which files will be processed and which names they'll be given:
echo -e ">>> INPUT: This script will process files from the metafile:\n\t$1"
echo -e ">>> PLAN: This script will process the sample files into the following names: "
echo -e "\t SAMPLE_READ_1 \t SAMPLE_READ_2 \t NAMES"

for (( counter=0; counter < ${#sample1[@]}; counter++ ))
do
    echo -e "\t ${sample1[$counter]}\t ${sample2[$counter]}\t ${names[$counter]}"
done

 # FASTP to determine quality
 echo -e "\n >>> FASTP: analyzing quality of each .fastq file"

 fastp="singularity run $container fastp"

 for (( counter=0; counter < ${#sample1[@]}; counter++ ))
 do
    samplename=${names[$counter]}
    echo -e "\n Sample Name: $samplename"

    read1=${sample1[$counter]}
    echo -e "\n Read 1: $read1"

    read2=${sample2[$counter]}
    echo -e "\n Read 2: $read2"     

    #Make trimmed fastq output directories
    fastpTrim="$outputdir/02_fastp_trim/$samplename"
    mkdir -p $fastpTrim
    echo -e "\n FASTP trimmed files are located in:\n $fastpTrim"

    #Make fastp report directories
    fastpReport="$outputdir/01_fastp_reports"
    mkdir -p $fastpReport
    echo -e "\n FASTP quality reports are located in:\n $fastpReport"

    ## execute fastp
    cmd1="$fastp -i ${inputdir}/${read1}${suffix} -I ${inputdir}/${read2}${suffix} -o ${fastpTrim}/${read1}_trim${suffix} -O ${fastpTrim}/${read2}_trim${suffix} --json=${fastpReport}/${read1}_report.json --html=${fastpReport}/${read1}_report.html -g -x -p"
    # input is read 1 (-i) and read 2 (-I) of sample, output is trimmed read 1 and read 2 and quality report for the pair.
    # options: 
    # -g (trim poly g)
    # -x (trim poly X tail, ie. polyT or polyA)
    # -p (overrepresented sequence analysis)
    # --adapter_fasta (specify a fasta file containing a list of possible sequences to trim)
    echo -e "\t $ ${cmd1}"
    time eval $cmd1
done

# HISAT2 to align to the genome
echo -e "\n>>> HISAT2: aligning each sample to the genome"
outhisat2="$outputdir/03_hisat2"
mkdir -p $outhisat2
echo -e "Alignment output located in directory $outhisat2"

hisat2="singularity run $container hisat2"

## create a temporary directory so that hisat2 can 
## write its core files without interfering with parallel runs
currentdir=$(realpath $(pwd))
tempdir=$(realpath $(mktemp -d .hisat2.XXXX))

for (( counter=0; counter < ${#sample1[@]}; counter++ ))
do
    samplename=${names[$counter]}
    echo -e "\n Sample name: $samplename"
    read1=${sample1[$counter]}_trim
    echo "Read 1: $read1"
    read2=${sample2[$counter]}_trim
    echo "Read 2: $read2"
    fastpTrim=$(realpath "$outputdir/02_fastp_trim/"$samplename/)

    ## execute hisat2, with absolute pathnames resolved in case of difficulties with the change of directory
    cmd3="$hisat2 -x $(realpath $hisat2path) -1 $(realpath ${fastpTrim}${read1}${suffix}) -2 $(realpath ${fastpTrim}${read2}${suffix}) -S $(realpath ${outhisat2}${read1}.sam) --summary-file $(realpath ${outhisat2}${read1}_summary.txt) --un-conc $(realpath ${outhisat2}${read1}_unaligned.sam) -p $pthread"
    echo -e "\t$ $cmd3"
    cd $tempdir
    time eval $cmd3
    cd $currentdir
done

# in case the loop quits before this command is run
cd $currentdir

# FEATURECOUNTS to tabulate reads per gene:
echo -e "\n>>> FEATURECOUNTS: Run featureCounts on all files to tabulate read counts per gene"
outfeature=$outputdir"04_feature/"
mkdir -p $outfeature
echo -e "Tabulation output files are located in: $outfeature"

# Acquire a list of .sam names
samfilePath=()
echo "Acquire .sam file names"
for (( counter=0; counter < ${#names[@]}; counter++ ))
do
    samfile=${sample1[$counter]}_trim.sam
    echo "File: $samfile"
    samfilePath+=(${outhisat2}${samfile})
    echo "Path: ${samfilePath[$counter]}"

done

# Execute featureCounts
featureCounts="singularity run $container featureCounts"
cmd4="$featureCounts -p -Q 20 -T ${pthread} -a $gtffile -o ${outfeature}counts.txt ${samfilePath[*]}"
echo -e "\n \t $ $cmd4"
time eval $cmd4

# SAMTOOLS and BAMCOVERAGE: to convert .sam output to uploadable .bam and .wg files
echo -e "\n>>> SAMTOOLS/BAMCOVERAGE: to convert files to uploadable _sort.bam and _sort.bam.bai files:"
samout=$outputdir"05_samtools/"
mkdir -p $samout
echo -e "\t Samtools output files located in: $samout"
samtools="singularity run $container samtools"
bamCoverage="singularity run $container bamCoverage"

for seqname in ${sample1[@]}
do
    echo -e "\n >>> Converting Filex: ${seqname}"
    
    # Samtools: compress .sam -> .bam
    cmd5="$samtools view --threads $pthread -bS ${outhisat2}${seqname}_trim.sam > ${samout}${seqname}_trim.bam"
  echo -e "\t $ ${cmd5}"
  time eval $cmd5
  
    
    # Samtools: sort .bam -> _sort.bam
    cmd6="$samtools sort --threads $pthread -o ${samout}${seqname}_trim_sort.bam --reference $genomefa ${samout}${seqname}_trim.bam"
    echo -e "\t$ ${cmd6}"
    time eval $cmd6
    
    
    # Samtools: index _sort.bam -> _sort.bam.bai
    cmd7="$samtools index ${samout}${seqname}_trim_sort.bam"
    echo -e "\t$ ${cmd7}"
    time eval $cmd7
    
    
    # bamCoverage: 
    cmd8="$bamCoverage -b ${samout}${seqname}_trim_sort.bam -o ${samout}${seqname}_trim_sort.bw --outFileFormat bigwig -p $pthread --normalizeUsing CPM --binSize 1"
    echo -e "\t$ ${cmd8}"
    time eval $cmd8
done


######## VERSIONS #############
echo -e "\n>>> VERSIONS:"
echo -e "\n>>> FASEQC VERSION:"
$fastqc --version
echo -e "\n>>> HISAT2 VERSION:"
$hisat2 --version
echo -e "\n>>> SAMTOOLS VERSION:"
$samtools --version
echo -e "\n>>> FEATURECOUNTS VERSION:"
$featureCounts -v
echo -e "\n>>> BAMCOVERAGE VERSION:"
$bamCoverage --version
echo -e ">>> END: Analayzer complete."
